FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY server ./server
COPY tsconfig.json ./

EXPOSE 3001
CMD ["npm", "run", "start"]
