/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderRouteImport } from './routes/order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsOrthoSheetRouteImport } from './routes/products/ortho-sheet'
import { Route as ProductsOrthoOralKitRouteImport } from './routes/products/ortho-oral-kit'
import { Route as ProductsLShapedInterdentalBrushRouteImport } from './routes/products/l-shaped-interdental-brush'
import { Route as ProductsH2oWaterFlosserRouteImport } from './routes/products/h2o-water-flosser'
import { Route as ProductsElectricalDentalBrushRouteImport } from './routes/products/electrical-dental-brush'

const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsOrthoSheetRoute = ProductsOrthoSheetRouteImport.update({
  id: '/products/ortho-sheet',
  path: '/products/ortho-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsOrthoOralKitRoute = ProductsOrthoOralKitRouteImport.update({
  id: '/products/ortho-oral-kit',
  path: '/products/ortho-oral-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLShapedInterdentalBrushRoute =
  ProductsLShapedInterdentalBrushRouteImport.update({
    id: '/products/l-shaped-interdental-brush',
    path: '/products/l-shaped-interdental-brush',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsH2oWaterFlosserRoute = ProductsH2oWaterFlosserRouteImport.update({
  id: '/products/h2o-water-flosser',
  path: '/products/h2o-water-flosser',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsElectricalDentalBrushRoute =
  ProductsElectricalDentalBrushRouteImport.update({
    id: '/products/electrical-dental-brush',
    path: '/products/electrical-dental-brush',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/products/electrical-dental-brush': typeof ProductsElectricalDentalBrushRoute
  '/products/h2o-water-flosser': typeof ProductsH2oWaterFlosserRoute
  '/products/l-shaped-interdental-brush': typeof ProductsLShapedInterdentalBrushRoute
  '/products/ortho-oral-kit': typeof ProductsOrthoOralKitRoute
  '/products/ortho-sheet': typeof ProductsOrthoSheetRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/products/electrical-dental-brush': typeof ProductsElectricalDentalBrushRoute
  '/products/h2o-water-flosser': typeof ProductsH2oWaterFlosserRoute
  '/products/l-shaped-interdental-brush': typeof ProductsLShapedInterdentalBrushRoute
  '/products/ortho-oral-kit': typeof ProductsOrthoOralKitRoute
  '/products/ortho-sheet': typeof ProductsOrthoSheetRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/products/electrical-dental-brush': typeof ProductsElectricalDentalBrushRoute
  '/products/h2o-water-flosser': typeof ProductsH2oWaterFlosserRoute
  '/products/l-shaped-interdental-brush': typeof ProductsLShapedInterdentalBrushRoute
  '/products/ortho-oral-kit': typeof ProductsOrthoOralKitRoute
  '/products/ortho-sheet': typeof ProductsOrthoSheetRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/order'
    | '/products/electrical-dental-brush'
    | '/products/h2o-water-flosser'
    | '/products/l-shaped-interdental-brush'
    | '/products/ortho-oral-kit'
    | '/products/ortho-sheet'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/order'
    | '/products/electrical-dental-brush'
    | '/products/h2o-water-flosser'
    | '/products/l-shaped-interdental-brush'
    | '/products/ortho-oral-kit'
    | '/products/ortho-sheet'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/order'
    | '/products/electrical-dental-brush'
    | '/products/h2o-water-flosser'
    | '/products/l-shaped-interdental-brush'
    | '/products/ortho-oral-kit'
    | '/products/ortho-sheet'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OrderRoute: typeof OrderRoute
  ProductsElectricalDentalBrushRoute: typeof ProductsElectricalDentalBrushRoute
  ProductsH2oWaterFlosserRoute: typeof ProductsH2oWaterFlosserRoute
  ProductsLShapedInterdentalBrushRoute: typeof ProductsLShapedInterdentalBrushRoute
  ProductsOrthoOralKitRoute: typeof ProductsOrthoOralKitRoute
  ProductsOrthoSheetRoute: typeof ProductsOrthoSheetRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ortho-sheet': {
      id: '/products/ortho-sheet'
      path: '/products/ortho-sheet'
      fullPath: '/products/ortho-sheet'
      preLoaderRoute: typeof ProductsOrthoSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ortho-oral-kit': {
      id: '/products/ortho-oral-kit'
      path: '/products/ortho-oral-kit'
      fullPath: '/products/ortho-oral-kit'
      preLoaderRoute: typeof ProductsOrthoOralKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/l-shaped-interdental-brush': {
      id: '/products/l-shaped-interdental-brush'
      path: '/products/l-shaped-interdental-brush'
      fullPath: '/products/l-shaped-interdental-brush'
      preLoaderRoute: typeof ProductsLShapedInterdentalBrushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/h2o-water-flosser': {
      id: '/products/h2o-water-flosser'
      path: '/products/h2o-water-flosser'
      fullPath: '/products/h2o-water-flosser'
      preLoaderRoute: typeof ProductsH2oWaterFlosserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/electrical-dental-brush': {
      id: '/products/electrical-dental-brush'
      path: '/products/electrical-dental-brush'
      fullPath: '/products/electrical-dental-brush'
      preLoaderRoute: typeof ProductsElectricalDentalBrushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OrderRoute: OrderRoute,
  ProductsElectricalDentalBrushRoute: ProductsElectricalDentalBrushRoute,
  ProductsH2oWaterFlosserRoute: ProductsH2oWaterFlosserRoute,
  ProductsLShapedInterdentalBrushRoute: ProductsLShapedInterdentalBrushRoute,
  ProductsOrthoOralKitRoute: ProductsOrthoOralKitRoute,
  ProductsOrthoSheetRoute: ProductsOrthoSheetRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
